#!/bin/sh
set -eu

: "${LAN_IF:?}"
: "${VPN_IF:?}"
: "${VPN_NET:?}"
: "${LOCAL_NETS:?}"

iptables -F
iptables -t nat -F
iptables -t mangle -F
iptables -X

iptables -P INPUT ACCEPT
iptables -P FORWARD DROP
iptables -P OUTPUT ACCEPT

# clamp TCP MSS for traffic going into VPN
iptables -t mangle -A FORWARD -o "$VPN_IF" -p tcp --tcp-flags SYN,RST SYN -j TCPMSS --clamp-mss-to-pmtu

# established/related first
iptables -A FORWARD -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT

# LAN -> VPN
iptables -A FORWARD -s "$VPN_NET" -i "$LAN_IF" -o "$VPN_IF" -j ACCEPT

# VPN_NET <-> LOCAL_NETS
for net in $LOCAL_NETS; do
    iptables -A FORWARD -s "$VPN_NET" -d "$net" -i "$LAN_IF" -o "$LAN_IF" -j ACCEPT
    iptables -A FORWARD -s "$net" -d "$VPN_NET" -i "$LAN_IF" -o "$LAN_IF" -j ACCEPT
done

# NAT for VPN
iptables -t nat -A POSTROUTING -s "$VPN_NET" -o "$VPN_IF" -j MASQUERADE